### ISSUE TITLE
Usage for disjunctive formulation

### ISSUE THREAD

**Issue by matbesancon** [SCIP-Interfaces/SCIP.jl#112]
SCIP and SCIP.jl support disjunctive formulations:
https://github.com/SCIP-Interfaces/SCIP.jl/blob/master/src/wrapper/cons_disjunction.jl

However, it's not clear from the signature how the API works, including expected types at each point.

To be fair, I'm not sure it's a SCIP.jl or SCIP core issue, I'll close it if considered unnecessary

**Comment by matbesancon** [comment]
same thing for indicator constraints

**Comment by leethargo** [comment]
The files in the `wrapper` directory are all automatically generated wrappers from the SCIP headers (by Clang.jl). So the signature is exactly the same as described in the SCIP docs.

If you want to use these types of constraints, it would be best to create wrapper functions, to deal with memory management and conversion from `MOI.VariableIndex` to `Ptr{SCIP_VAR}` etc. In order to support the constraints through `MOI` (and `JuMP`), one would have to define more things, e.g., an `MOI.AbstractVectorSet` or similar.

I did this already for `cons_abspower`, see [MOI_wrapper/abspower_constraints.jl](https://github.com/SCIP-Interfaces/SCIP.jl/blob/master/src/MOI_wrapper/abspower_constraints.jl).

Personally, I find `cons_indicator` quite useful, so I might add the wrapper myself now. For `cons_disjunction`, I'm not aware of anybody ever using it, so it might not be as powerful as we might hope ;-) Maybe it does not do much more than branching.

If you already have an idea for an MOI-facing API, I'd would be happy to hear it.

**Comment by matbesancon** [comment]
> The files in the wrapper directory are all automatically generated wrappers from the SCIP headers (by Clang.jl). So the signature is exactly the same as described in the SCIP docs.

Yeah TBH I struggled a bit with reading the SCIP doc for these.

Thanks for the abspower example. I think most problems requiring disjunctions can be handled using indicators. In my case it was more natural with the former but it must be equivalent from a computational point of view.

I'll try to PR on this soon

**Comment by leethargo** [comment]
OK, cool. Let me know if you want to discuss it further.

If I remember correctly, in order to create an indicator constraint in SCIP, one has to first create (but not add!) a linear constraint and then pass its `SCIP_CONS*` into the indicator constraint. I guess that the indicator constraint can then take the (sole) responsibility of the reference counting.

> I think most problems requiring disjunctions can be handled using indicators.

Yes, if you want to do mostly disjunctions of linear constraints. AFAIK, SCIP can handle disjunctions of arbitrary constraint types.

**Comment by matbesancon** [comment]
I think we can close this given #113, even though it's not strictly the same
