### ISSUE TITLE
build with SCIP7

### ISSUE THREAD

**Issue by kibaekkim** [SCIP-Interfaces/SCIP.jl#152]
I was not able to build `SCIP.jl` with scipoptsuite-7.0.0. It looks like the build found the library, but could not do more.
```
┌ Error: Error building `SCIP`:
│ ERROR: LoadError: Unable to locate SCIP installation.
│ Tried:
│ 	/homes/kibaekkim/SCIP/scipoptsuite-7.0.0/build/lib/libscip.so
│ 	libscip.so
│ Note that this must be downloaded separately from scip.zib.de.
│ Please set the environment variable SCIPOPTDIR to SCIP's installation path.
│
│ Stacktrace:
│  [1] error(::String) at ./error.jl:33
│  [2] top-level scope at /homes/kibaekkim/.julia/packages/SCIP/lczBF/deps/build.jl:43
│  [3] include at ./boot.jl:328 [inlined]
│  [4] include_relative(::Module, ::String) at ./loading.jl:1094
│  [5] include(::Module, ::String) at ./Base.jl:31
│  [6] include(::String) at ./client.jl:431
│  [7] top-level scope at none:5
│ in expression starting at /homes/kibaekkim/.julia/packages/SCIP/lczBF/deps/build.jl:42
└ @ Pkg.Operations /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.2/Pkg/src/backwards_compatible_isolation.jl:647
  Building TimeZones → `~/.julia/packages/TimeZones/X323b/deps/build.log`
```

Note that I can still build with scipoptsuite-6.0.2.

**Comment by rschwarz** [comment]
Are you building SCIP from source?

SCIP.jl needs version 0.9.4 to work with SCIP 7.0.0. From the error message you shared, I gather that you must have an older version of SCIP.jl, since I [changed it](https://github.com/SCIP-Interfaces/SCIP.jl/pull/149/files#diff-ed74277d7f2e98f12cf51e6b8be90705R46) to include the error message from `dlopen`.

Maybe some of the dependencies can't be found, such as `tbb`.

**Comment by kibaekkim** [comment]
Sorry. I was using an old version. New version works well. Thanks!
